name: firestore_api_parser
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.1.0
  meta: ^1.7.0

#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^5.0.2
  lints: ^1.0.1
  test: ^1.16.0
